[package]
name = "atlas-assembler"
version = "0.1.0"
edition = "2024"

[dependencies]
atlas-isa = { path = "../atlas-isa" }
atlas-files = { path = "../atlas-files" }
atlas-inspect = { path = "../atlas-inspect" }
